"""empty message

Revision ID: 288b78d4b443
Revises: f7065ee366b5
Create Date: 2021-10-20 12:45:50.216764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288b78d4b443'
down_revision = 'f7065ee366b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'user', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follow', 'user', ['followed_id'], ['id'])
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('rol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rol')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'post', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'user', ['followed_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'follow', 'user', ['follower_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
